apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}-{{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Chart.Name}}
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
