apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}-svc
spec:
  type: NodePort
  selector:
    app: {{.Release.Name}}-{{.Chart.Name}}
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{.Values.service.port}}
