apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: node-app:1.0.9
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST    # Notice that the case is different here
                              # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: myapp     # The ConfigMap this value comes from.
              key: redis_host # The key to fetch.
        - name: WEB_PORT    # Notice that the case is different here
                              # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: myapp     # The ConfigMap this value comes from.
              key: web_port # The key to fetch.
